[project]
name = "ddr-cmdln"
description = "Densho Digital Repository core tools"
authors = [
    {name = "Geoffrey Jost", email = "geoffrey.jost@densho.us"}
]
maintainers = [
    {name = "Geoffrey Jost", email="geoffrey.jost@densho.us"},
]
readme = "README.rst"
license = {file = "LICENSE"}
keywords = ["repository"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Environment :: Console",
    "License :: TBD",
    "Topic :: Other/Nonlisted Topic",
    "Topic :: Sociology :: History",
]

dynamic = ["version"]  # will read __version__ from DDR/__init__.py
requires-python = ">=3.13"
# Non-Python dependencies
# sudo apt-get install imagemagick libexempi8 libxml2-dev python-dev pmount udisks
# Elasticsearch 2.4.3
dependencies = [
    "beautifulsoup4==4.12.3",      # MIT
    "b2sdk==2.9.4",                # MIT      y
    "bpython==0.26",
    "click==8.3.3",                # BSD      y
    "deepdiff==8.6.1",             # MIT      y
    "envoy==0.0.3",                # MIT             TODO replace!
    "gitpython==3.1.46",           # BSD
    "httpx2==2.0.0",               # BSD
    "humanize==4.10.0",            # MIT
    "internetarchive==5.8.0",
    "jinja2==3.1.6",               # BSD
    "natsort==8.1.0",              # MIT
    "psutil==5.9.8",               # BSD      y
    "python-dateutil==2.9.0.post0",# BSD
    "python-xmp-toolkit==2.1.0",   # New BSD
    "elastictools @ git+https://github.com/denshoproject/densho-elastictools.git@v1.0.2",
]

[project.optional-dependencies]
testing = [
    "mypy",
    "pytest==9.0.3",
    "pytest-cov==7.1.0",
]

[project.scripts]
ddr2 = "DDR.cli.ddr:ddr"
ddrcheck = "DDR.cli.ddrcheck:ddrcheck"
ddrcheckbinaries = "DDR.cli.ddrcheckbinaries:ddrcheckbinaries"
ddrcheckencoding = "DDR.cli.ddrcheckencoding:ddrcheckencoding"
ddrconfig = "DDR.cli.ddrconfig:ddrconfig"
ddrdesc = "DDR.cli.ddrdesc:ddrdesc"
ddrexport = "DDR.cli.ddrexport:ddrexport"
ddriaconvert = "DDR.cli.ddriaconvert:ddriaconvert"
ddrindex = "DDR.cli.ddrindex:ddrindex"
ddrinfo = "DDR.cli.ddrinfo:ddrinfo"
ddrinventory = "DDR.cli.ddrinventory:ddrinventory"
ddrimport = "DDR.cli.ddrimport:ddrimport"
ddrnames = "DDR.cli.ddrnames:ddrnames"
ddrpubcopy = "DDR.cli.ddrpubcopy:ddrpubcopy"
ddrremote = "DDR.cli.ddrremote:ddrremote"
ddrsignatures = "DDR.cli.ddrsignatures:ddrsignatures"
ddrtransform = "DDR.cli.ddrtransform:ddrtransform"
ddrvhfileprep = "DDR.cli.ddrvhfileprep:ddrvhfileprep"
ddrvocab = "DDR.cli.ddrvocab:ddrvocab"

[project.urls]
Repository = "https://github.com/denshoproject/ddr-cmdln"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.setuptools.package-data]
DDR = ["templates/*.tpl"]

[tool.setuptools.dynamic]
version = {file = "VERSION"}
